name: Unit Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  matrix:
    name: 'Node ${{ matrix.node }}'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [14, 16, 18]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: 'yarn'
      - name: Install dependencies
        uses: yarn install --frozen-lockfile
      - name: Unit Test
        run: yarn test

